### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by blackshot** [ZombieStriker/ServerRestorer#11]
https://github.com/ZombieStriker/ServerRestorer/blob/f8497cb9eeed9297dafe16dc913fede7418f1527/src/me/zombie_striker/sr/Main.java#L584

when i start saving with /sr save it shows me this waringn

`16.01 15:49:16 [Server] WARN java.io.FileNotFoundException: /backups/Bkp-2020-01-16-15-49-16.zip (Is a directory)
16.01 15:49:16 [Server] WARN at java.io.FileOutputStream.open0(Native Method)
16.01 15:49:16 [Server] WARN at java.io.FileOutputStream.open(FileOutputStream.java:270)
16.01 15:49:16 [Server] WARN at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
16.01 15:49:16 [Server] WARN at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
16.01 15:49:16 [Server] WARN at me.zombie_striker.sr.Main.zipFolder(Main.java:586)
16.01 15:49:16 [Server] WARN at me.zombie_striker.sr.Main$4.run(Main.java:399)
16.01 15:49:16 [Server] WARN at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
16.01 15:49:16 [Server] WARN at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
16.01 15:49:16 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
16.01 15:49:16 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
16.01 15:49:16 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
16.01 15:49:16 [Server] WARN at java.lang.Thread.run(Thread.java:748)`

config.yml
`getBackupFileDirectory: ''
saveServerJar: true
savePluginJars: true
AutosaveDelay: 1D
LastAutosave: 1579187581278
enableautoSaving: false
FileNameFormat: Bkp-%date%
prefix: '&6[&3ServerRestorer&6]&8'
kickMessage: '&6[&3ServerRestorer&6]&8 Restoring server to previous save. Please rejoin
  in a few seconds.'
EnableFTP: true
EnableFTPS: false
EnableSFTP: false
FTPAdress: [CENSORED]
FTPPort: 21
FTPUsername: [CENSORED]
FTPPassword: [CENSORED]
FTP_Directory: ''
exceptions:
- logs
- crash-reports
- backups
- dynamap
- pixelprinter
- backups
MaxSaveSize: 10G
MaxFileSaved: 2
DeleteZipOnFTPTransfer: true
DeleteZipIfFailed: false`

**Comment by blackshot** [comment]
fixed :)
