### ISSUE TITLE
Cannot translate null text

### ISSUE THREAD

**Issue by tomkimberlin** [ZombieStriker/ServerRestorer#2]
```
[01:41:08] [Server thread/ERROR]: Error occurred while enabling ServerRestorer v1.0.20 (Is it up to date?)
java.lang.IllegalArgumentException: Cannot translate null text
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.14.2.jar:git-Paper-70]
	at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:354) ~[patched_1.14.2.jar:git-Paper-70]
	at me.zombie_striker.sr.Main.onEnable(Main.java:113) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.2.jar:git-Paper-70]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.2.jar:git-Paper-70]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419) ~[patched_1.14.2.jar:git-Paper-70]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464) ~[patched_1.14.2.jar:git-Paper-70]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378) ~[patched_1.14.2.jar:git-Paper-70]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464) ~[patched_1.14.2.jar:git-Paper-70]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.14.2.jar:git-Paper-70]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:855) ~[patched_1.14.2.jar:git-Paper-70]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
```

Hey. Wanted to try out your plugin but I'm getting this error when launching my server.
Paper-70 1.14.2
ServerRestorer v1.0.20

**Comment by iusearch** [comment]
Same here. Cannot enable.

**Comment by ZombieStriker** [comment]
Seems one of the variables was misused. This error should now be fixed.
