### ISSUE TITLE
1.14.2 paper spigot 73 build failed to execute /sr command

### ISSUE THREAD

**Issue by iusearch** [ZombieStriker/ServerRestorer#3]
```
[10:38:20 INFO]: [ServerRestorer] Enabling ServerRestorer v1.0.20
[10:38:20 INFO]: [ChatManager] Enabling ChatManager v3.4.9
[10:38:20 INFO]: [ChatManager] Starting Metrics.
[10:38:20 INFO]: [ChatManager] Hooked into: Vault v1.7.2-b107
[10:38:36 INFO]: [ChatManager] Plugin is up to date - v3.4.9
[10:38:36 INFO]: =========================
[10:38:36 INFO]: Chat Manager
[10:38:36 INFO]: Version 3.4.9
[10:38:36 INFO]: Author: H1DD3NxN1NJA
[10:38:36 INFO]: =========================
[10:38:36 INFO]: [TradePlus] Enabling TradePlus v3.45
[10:38:36 INFO]: You appear to be running version 114
[10:38:37 INFO]: [AuthMe] Enabling AuthMe v5.6.0-SNAPSHOT-b2248
[10:38:37 INFO]: [AuthMe] SQLite Setup finished
[10:38:37 INFO]: [AuthMe] Hooked into LuckPerms!
[10:38:37 INFO]: [AuthMe] [LICENSE] This product includes GeoLite2 data created by MaxMind, available at https://www.maxmind.com
[10:38:37 INFO]: [AuthMe] AuthMe 5.6.0-SNAPSHOT build n.2248 correctly enabled!
[10:38:37 INFO]: [LockettePro] Enabling LockettePro v2.9.5-1.14
[10:38:37 WARN]: [LockettePro] BURNING_FURNACE is not a block!
[10:38:37 WARN]: [LockettePro] WOODEN_DOOR is not a block!
[10:38:37 WARN]: [LockettePro] IRON_DOOR_BLOCK is not a block!
[10:38:38 INFO]: Done (26.939s)! For help, type "help"
[10:38:38 INFO]: Timings Reset
[10:38:38 INFO]: [Vault] Checking for Updates ... 
[10:38:38 WARN]: A manual (plugin-induced) save has been detected while server is configured to auto-save. This may affect performance.
[10:38:41 INFO]: [Vault] No new version available
[10:38:50 WARN]: Unexpected exception while parsing console command "sr"
org.bukkit.command.CommandException: Cannot execute command 'sr' in plugin SkinsRestorer v13.7.0-SNAPSHOT - plugin is disabled.
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.14.2.jar:git-Paper-73]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.2.jar:git-Paper-73]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:736) ~[patched_1.14.2.jar:git-Paper-73]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:698) ~[patched_1.14.2.jar:git-Paper-73]
at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:457) ~[patched_1.14.2.jar:git-Paper-73]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:419) ~[patched_1.14.2.jar:git-Paper-73]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1061) ~[patched_1.14.2.jar:git-Paper-73]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:905) ~[patched_1.14.2.jar:git-Paper-73]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by iusearch** [comment]
The full command /serverrestorer can be executed.

**Comment by aliyuchang33** [comment]
Seems to be something wrong with paper not the plugin.
