### ISSUE TITLE
sftp error

### ISSUE THREAD

**Issue by Minecon724** [ZombieStriker/ServerRestorer#36]
```
06.05 13:51:50 [Server] WARN com.jcraft.jsch.JSchException: UnknownHostKey: 146.59.xx.xx. RSA key fingerprint is 50:1f:12:d1:94:2f:c0:dc:da:b7:db:a8:97:82:89:d4
06.05 13:51:50 [Server] WARN at com.jcraft.jsch.Session.checkHost(Session.java:805)
06.05 13:51:50 [Server] WARN at com.jcraft.jsch.Session.connect(Session.java:345)
06.05 13:51:50 [Server] WARN at me.zombie_striker.sr.Main$4.run(Main.java:470)
06.05 13:51:50 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
06.05 13:51:50 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
06.05 13:51:50 [Server] WARN at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
06.05 13:51:50 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
06.05 13:51:50 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
06.05 13:51:50 [Server] WARN at java.lang.Thread.run(Thread.java:748)

**Comment by PerchunPak** [comment]
also have same error
```
[16:05:59 INFO]: [ServerRestorer] FAILED TO SFTP TRANSFER FILE: Backup-2021-07-07-15-59-44.zip. ERROR IN CONSOLE.
[16:05:59 WARN]: com.jcraft.jsch.JSchException: UnknownHostKey: (here was ip). RSA key fingerprint is xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx (also cutted, im not sure is this public information)
[16:05:59 WARN]:        at com.jcraft.jsch.Session.checkHost(Session.java:805)
[16:05:59 WARN]:        at com.jcraft.jsch.Session.connect(Session.java:345)
[16:05:59 WARN]:        at me.zombie_striker.sr.Main$4.run(Main.java:453)
[16:05:59 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[16:05:59 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[16:05:59 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:05:59 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[16:05:59 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[16:05:59 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**Comment by Minecon724** [comment]
this plugin is dead
use this instead https://www.spigotmc.org/resources/drivebackupv2.79519/

**Comment by PerchunPak** [comment]
its too, half but dead
![image](https://user-images.githubusercontent.com/68118654/124993151-a2e53a00-e04c-11eb-997d-89e3759f1ff4.png)

**Comment by Minecon724** [comment]
at least it works
